### ISSUE TITLE
Defer Everything to System Class Loader Not Marked for Mock

### ISSUE THREAD

**Issue by EarthCitizen** [powermock/powermock#587]
When I use `@PrepareForTest(MyClass.class)`, I also have to put ignores for classes that do not function when the class loader is `PowerMock`:

`@PowerMockIgnore({"org.hsqldb.*", "javax.*", "org.apache.*", "org.springframework.*", "org.xml.*"})`

That gets excessive. I imagine this could also be done with a mock policy, but it is still a hassle. Is there a harm in `PowerMock` deferring everything to the system class loader that is not specifically marked for mock with `@PrepareForTest` or `@PrepareOnlyThisForTest`? This would greatly reduce the need for ignores.

**Comment by johanhaleby** [comment]
Hmm I'm not sure to be honest. Feel free to experiment with the [MockClassloader](https://github.com/jayway/powermock/blob/master/core/src/main/java/org/powermock/core/classloader/MockClassLoader.java) and [DeferSupportingClassLoader](https://github.com/jayway/powermock/blob/master/core/src/main/java/org/powermock/core/classloader/DeferSupportingClassLoader.java). If you manage to improve the situation that would be awesome and I'll gladly accept a pull request.

**Comment by ubuntudroid** [comment]
Shouldn't using the `PrepareOnlyThisForTest` annotation help in this situation? However I'm currently experimenting with it and still find many other (also non-framework) classes to be loaded by the Powermock class loader. Not sure why.

**Comment by thekingnothing** [comment]
@EarthCitizen, I agree with you that it's annoying add same list of ignoring pages for each test and it breaks DRY rule, but we cannot simple change behaviour of  `@PrepareForTest`, because it could affect other users how are using PowerMock. 

I think one of the following way can be used to address your issue 

- make global option which change behaviour the `@PrepareForTest` (see discussion #623). 
- add attribute to `@PrepareForTest` like (`onlyThese=false|true`)
- more option `@PowerMockIgnore` could be package level annotation. 

@ubuntudroid `@PrepareOnlyThisForTest` means a bit different thing that you think. From JavaDoc: 

> 
The difference between this annotation and the {@link PrepareForTest} annotation is that this annotation only modifies the specified classes whereas the {@link PrepareForTest} annotation manipulates the full class hierarchy. This annotation is recommend if you want full control over which classes that are byte-code manipulated.

**Comment by thekingnothing** [comment]
> Is there a harm in PowerMock deferring everything to the system class loader that is not specifically marked for mock with @PrepareForTest or @PrepareOnlyThisForTest

If PowerMock defers everything to the system class loader except classes that is pointed in `@PrepareForTest` or `@PrepareOnlyThisForTest`, when we have an issue with package-private classes, fields and methods.  Unfortunately, in Java class specified by pair <Class name, ClassLoader> and class can get access only to package-private classes/fields/methods which are loaded by the same ClassLoader. Otherwise, it's implied that class locates in other package even it has the same name.  
For example, if a class extends another package-private class. PowerMock cannot load only the class, but also should load its parent. In general it means that whole hierarchy should be scan during loading and loading other classes. And if this case, could be resolve (by introducing complexity, but could be), case with access to package-private fields/method cannot be resolve without scanning byte code of the class. 

I implemented ability to set global PowerMockIgnore via `configuration.properties` in PowerMock 1.7.0 (issue #801). So it partially fix your issues. You may now specify all ignores in one place.

**Comment by dumbdonkey** [comment]
@thekingnothing plz forgive my foolish, I cannot understand your example. Could you give a detailed explanation? thanks.
