### ISSUE TITLE
How do you run a single method?

### ISSUE THREAD

**Issue by yujishe** [powermock/powermock#794]
hi:
I have a question for run My test.I can run a single method when Use Mockito+JUnit.but I can Run a single method with powermock. 
when I　want run a single method, it's show a error.
this is error;
![image](https://cloud.githubusercontent.com/assets/22394316/26334651/12d6dffc-3f99-11e7-90b2-1d2c2960fe93.png)
It's my code
```
@RunWith(PowerMockRunner.class)
public class ClassFinalTest {
    
    @Test
    @PrepareForTest(CallStatic.class)
    public void testCallstaticMethod() {
	CallArgument callArgument = new CallArgument();
	PowerMockito.mockStatic(CallStatic.class);
	PowerMockito.when(CallStatic.isExist()).thenReturn(true);
	boolean result = callArgument.callstaticMethod();
	Assert.assertTrue(result);
    }
    
    @Test
    @PrepareForTest(ClassFinal.class)
    public void testCallFinalMethod() {
	CallArgument callArgument = new CallArgument();
	ClassFinal classFinal = PowerMockito.mock(ClassFinal.class);
	PowerMockito.mockStatic(ClassFinal.class);
	PowerMockito.when(classFinal.isAlive()).thenReturn(true);
	boolean result = callArgument.callFinalMethod(classFinal);
	Assert.assertTrue(result);
    }
    
}
```
If you have time, I have a few questions to ask.First question: can the powermock and mockito framework be used in the same method?
Second question: can powermock be used with spring-mock?If so, does the @mock annotation conflict?
I really need the answers to these questions, and maybe these questions seem to you to be so weak.
happy mock!

**Comment by thekingnothing** [comment]
Sometimes, as in your case IDE cannot detected test case correctly when PowerMock is used. I'd like to recommend to move `@PrepareForTest(ClassFinal.class, CallStatic.class)` on class level, because when you it on method level and test chunk is created and each test case runs with separated class loader, so it also could affect. 
Of course, you can use PowerMock and Mockito in one method. 
I've never use `spring-mock`, so I cannot help you with it. better to search this information on stackoverflow.

**Comment by yujishe** [comment]
@thekingnothing  
Thank you for your response, and I successfully completed the test through your solution.
