### ISSUE TITLE
Powermockito 1.7.3, incompatible with mockito 2.10.0

### ISSUE THREAD

**Issue by michelbetancourt** [powermock/powermock#857]
We ran into an issue where Powermockito 1.7.3 is not compatible with Mockito 2.10.0.

The workaround is to downgrade to Mockito 2.9.0.

Sample test case:

```
@RunWith(PowerMockRunner.class)
@PrepareForTest({ StaticClass.class })
public class LoggerHealthIndicatorTest {

  public static class StaticClass {
      public static String callStatic() {
           return "dummy value";
      }
  }
 @Test
    public void testDefaultAction_Fails_WithForceHeader() throws Exception {
        PowerMockito.mockStatic(StaticClass.class);
        when(StaticClass.callStatic())
                .thenReturn("any value");
        TestFixture.call();
        PowerMockito.verifyStatic(StaticClass.class);
    }
}

```

**Comment by thekingn0thing** [comment]
Yes, you are right. PowerMock 1.x cannot work with Mockito 2.10.x, because Mockito 2.10.x contains significant changes in internal API (https://github.com/mockito/mockito/issues/1110) which was done to provide Public API for PowerMock (#726). Only PowerMock 2.x will work with further versions of Mockito.

**Comment by michelbetancourt** [comment]
No no, apologies.  This is powermockito2 not powermockito 1.  I was not specific enough.  Please re-open.

**Comment by michelbetancourt** [comment]
I opened a new related issue with more clarity.  Apologies but that should help.
